customhost = "customerdb.cxgceeag8niw.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Admin123"
customdb = "project_db"
custombucket = "project-bucket-autohub"
customregion = "us-east-1"
